1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]


In [22]:
import numpy as np
import os
import hashlib
#Function to find duplicate files
def findDuplicate(path):
    hashedFilePath = {}
    for root, dirName, files in os.walk(path):
        for file in files:
            filePath = os.path.join(root, file)
            with open(filePath, 'rb') as f:
                fileHash = hashlib.sha256(f.read()).hexdigest()
            if fileHash in hashedFilePath:
                hashedFilePath[fileHash].append(filePath)
            else:
                hashedFilePath[fileHash] = [filePath]
    return {fileHash:filePath for fileHash, filePath in hashedFilePath.items() if len(filePath) > 1}
# path = input("Enter file path: ")
path = "C:/Users/arysingh/OneDrive - ALLEGIS GROUP/Desktop/Test"
duplicateFiles = findDuplicate(path)
if len(duplicateFiles) == 0:
    print("No Duplicate Files")
else:
    #removing duplicate files
    for fileHash, filePath in duplicateFiles.items():
        print(f"fileHash : {fileHash}")
        for file in filePath[:-1]:
            os.remove(file)

No Duplicate Files


2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]


In [11]:
from random import *
lc=uc=dc=sc=0
ans=""
while(len(ans)<6):
    num=randint(0,4)
    if num==0 and lc<2:
        ans+=chr(randint(97,122))
        lc+=1
    elif num==1 and uc<1:
        char=chr(randint(97,122))
        ans+=char.upper()
        uc+=1
    elif num==2 and dc<3:
        ans+=str(randint(0,9))
        dc+=1
    elif num==3 and sc<1:
        ans+=chr(randint(33,47))
        sc+=1

print("Random Password : "+ans)

Random Password : sz-K83


3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [35]:
def prime(x):
    if x < 2:
        return False
    for i in range(2, x):
        if x % i == 0:
            return False
    return True

def Solution():
    k=0
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            if prime(k):
                mat[i,j] = (k) ** 3
            k+=1
    return mat

# row = int(input("enter the number of rows :"))
# col = int(input("enter the number of cols :"))
row=8
col=4
mat=(np.arange(row*col)).reshape(row,col)
# mat=np.ones((row,col),dtype='int32')
answer_matrix=Solution()
answer_matrix

array([[    0,     1,     8,    27],
       [    4,   125,     6,   343],
       [    8,     9,    10,  1331],
       [   12,  2197,    14,    15],
       [   16,  4913,    18,  6859],
       [   20,    21,    22, 12167],
       [   24,    25,    26,    27],
       [   28, 24389,    30, 29791]])

4.	Python program to get the sum of every cubed value and its previous integer. 

In [42]:
def findSum(mat2, k ):
    ans=[]
    for i in range(mat2.shape[0]):
        for j in range(mat2.shape[1]):
            
            if prime(k):
                sum1=0
                if j>0:
                    sum1+= mat2[i][j-1]
                else:
                    sum1+=mat2[i-1][mat2.shape[1]-1]
                    
                mat2[i][j]+=sum1
                
            k += 1
findSum(answer_matrix,0)
answer_matrix

array([[    0,     1,     9,    36],
       [    4,   129,     6,   349],
       [    8,     9,    10,  1341],
       [   12,  2209,    14,    15],
       [   16,  4929,    18,  6877],
       [   20,    21,    22, 12189],
       [   24,    25,    26,    27],
       [   28, 24417,    30, 29821]])

5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]

             arr2[] = [2, 3, 5, 6]


In [20]:
def findIntersection(nums1, nums2, intersectionArr):
    for num in nums1:
        if num in nums2:
            intersectionArr.append(num)
    return intersectionArr

nums1 = list(map(int, input().split()))
nums2 = list(map(int, input().split()))
intersectionArr = []
findIntersection(nums1, nums2, intersectionArr)

8 7 8 8 6 5 99
99 7 8 8 


[8, 7, 8, 8, 99]

6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [43]:
# row = int(input("enter the number of rows :"))
# col = int(input("enter the number of cols :"))
row=7
col=7
mat=(np.arange(0,49)).reshape(row,col)
mat
mat = [[7*(i+j) for i in range(row)]for j in range(0, col)]
# print(mat)
print(mat[6][6])
mat

84


[[0, 7, 14, 21, 28, 35, 42],
 [7, 14, 21, 28, 35, 42, 49],
 [14, 21, 28, 35, 42, 49, 56],
 [21, 28, 35, 42, 49, 56, 63],
 [28, 35, 42, 49, 56, 63, 70],
 [35, 42, 49, 56, 63, 70, 77],
 [42, 49, 56, 63, 70, 77, 84]]

7.	Checker Board Patten using Numpy:
[

    1   0   1   0   1   0   1

    0   1   0   1   0   1   0
    
    1   0   1   0   1   0   1
    
    0   1   0   1   0   1   0
    
    1   0   1   0   1   0   1  ]


In [46]:
import numpy as np
def checkerBoard(x, y):
    npArr = np.ones((x, y),dtype='int16')
    npArr[1::2, ::2] = 0
    npArr[::2, 1::2] = 0
    return npArr

x=y=5
mat=checkerBoard(x, y)
mat

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int16)

8.	Create a given Matrix:
[  A,     B,     C,       D

   E,      F,     G,       H
   
    I,      a,      K,       L
    
   M,    N,     o,       P
   
   Q,     R,      S,       T
   
   U,     0,     W,      O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values


In [3]:
arr_6=list("ABCDEFGHIJKLMNOPQRSTUVWX")
arr_7=list("AEIOU")
# arr_6.reshape(4,6)
# arr_7
j=0
for i in range(0,len(arr_6)):
    if j<len(arr_7) and arr_6[i]==arr_7[j]:
        j+=1
        arr_6[i]=np.nan

arr_6=np.array(arr_6)
arr_6=list(arr_6)
# arr_6=arr_6.reshape(4,6)
print(arr_6)
count=0
for i in arr_6:
        if i=='nan':
           count += 1
print("count of the missing values :",count)

['nan', 'B', 'C', 'D', 'nan', 'F', 'G', 'H', 'nan', 'J', 'K', 'L', 'M', 'N', 'nan', 'P', 'Q', 'R', 'S', 'T', 'nan', 'V', 'W', 'X']
count of the missing values : 5
